Improvements to tests
myriadrf/LimeSuiteNG pull request #15
Opened 2024-04-05 09:37 UTC by DominykasPetke

# Changed
- Device tests to actually connect to the device and receive test pattern data
- Updated GTest

# Fixed
- Clang code coverage generation
- A few bugs in USB communications code

2024-04-07 12:12 UTC, rjonaitis requested changes
All these tests are identical, so it shouldn't be device specific. This is more like a runtime tests of the API.

Device specific testing, that tests actual hardware if it functions properly will not be done using GTest, it will be a standalone application.

2024-04-07 12:12 UTC, rjonaitis commented on src/tests/boards/LimeSDR/LimeSDRTest.cpp
> +    // Samples can begin at any point in the sequence, so we're finding a common start point first.
This strategy skips data verification before the "common" point, so it will pass even if the starting data would be invalid.
The correct strategy to test the "test signal", would be to take the first received complex sample, and generate the expected sequence from that point.
The test sequence is sinusoidal wave sampled at configured time intervals:
So if the TestSignal::Divide is Div4, the sampling phase difference will be (2pi / 4). That makes the next sample in the sequence to be the previous complex(i,q) rotated by (2pi/4).

2024-04-08 14:11 UTC, DominykasPetke commented
I would prefer to still have these tests exist here for the time being (until the mentioned standalone testing application is working) just to have some assurance that devices are actually being connected to and function properly in a consistent, non-GUI reliant manner.

2024-04-08 14:13 UTC, DominykasPetke commented on src/tests/boards/LimeSDR/LimeSDRTest.cpp
> +    // Samples can begin at any point in the sequence, so we're finding a common start point first.
Got it to work, but it seems like it needs a 1-2 bit (in 12-bit space, so 16 or 32 in 16-bit space) delta allowance for it to account for floating point inaccuracies properly.

2024-04-09 07:57 UTC, merged