Add a DMA USB wrapper
myriadrf/LimeSuiteNG pull request #32
Opened 2024-05-10 07:34 UTC by DominykasPetke

# Added
- USB DMA wrapper
- A DMA interface class

# Changed
- Merged PCIe TRX Looper code with the main looper code and made it based on the DMA interface
- USB devices use the singular remaining TRX Looper
- Made `LitePCIe` inherit the DMA interface
- Split interfaces in IComms into their own separate files
- Simplified a few pieces of code for ease of reading

# Fixed
- USB enumeration not filtering devices properly on Windows

# Removed
- USB-specific TRX Looper

# Known issues
- Hacky workaround to set packet size in the FPGA for PCIe devices only
- Samples transmission stops after a few seconds on USB devices on Linux
- Windows issues, receiving sometimes working sometimes not, might be related to if a wait is triggered two times (first via `Wait()` then via `CacheFlush()`)

2024-05-10 07:35 UTC, DominykasPetke commented
Putting this in as a draft for now as I feel like a fresh pair of eyes would be quite beneficial at this point, as this does have a workaround that should not be in the final code but have no place to put it in a clean way, as well as probably a few misunderstandings on how DMA actually works, and a few issues I do not have a clear idea on how to fix, and probably some issues I don't even know about

2024-05-15 05:47 UTC, DominykasPetke commented
@rjonaitis Not sure if you've seen this

2024-05-16 08:04 UTC, rjonaitis requested changes

2024-05-16 08:04 UTC, rjonaitis commented on src/tests/protocols/BufferInterleavingTest.cpp
> +template<typename... Ts> constexpr std::array<std::byte, sizeof...(Ts)> make_bytes(const Ts&&... args) noexcept
PR is suppose to be focused about USB streaming wrapped with DMA interface. Changes like this are unnecessary. Also adding std::byte, it does not add any benefits in this situation and just overcomplicates things, now this needs variadic templates just to initialize the arrays.

2024-05-16 08:04 UTC, rjonaitis commented on src/protocols/TRXLooper.cpp
> +    // only if PCIe device
Variable Rx packet size feature is determined by the device gateware, so this should be made as a capability flag or function in the FPGA class, which could be enabled by the device when creating the fpga object.

2024-05-16 08:04 UTC, rjonaitis commented on src/comms/USB/USBDMA.cpp
> +void USBDMA::CacheFlush(TRXDir samplesDirection, DataTransferDirection dataDirection, uint16_t index)
USB does not have DMA capability, so it does not need to instruct CPU caches flushing, because this is just only immitating DMA interface, flushing should do nothing.
Flushing is only required when PCIe DMA is used, as the CPU and device is sharing RAM access, the CPU may have cached some of the RAM memory values and is not aware that peripheral device may have modified it at some point.

2024-05-16 08:04 UTC, rjonaitis commented on src/comms/USB/USBDMA.cpp
> +void USBDMA::TxStartTransferThread()
Dedicated transmitting thread is not required.
You can initiate Tx BeginDataXfer when buffer values have been filled and then DMA state is being updated with counter increment.

2024-05-16 08:04 UTC, rjonaitis commented on src/comms/USB/USBDMA.cpp
> +void USBDMA::RxStartTransferThread()
Dedicated Rx thread is also not required.
When RxDMA is enabled, request the initial batch of transfers. Then request next transfer, when Rx updates the DMA state with incremented software counter.

2024-06-05 10:41 UTC, merged