Rewrite driver device path management
myriadrf/LimeSuiteNG pull request #33
Opened 2024-05-15 15:54 UTC by CoffeeLexer

- Fixed udev-rules being not applied
- Renamed litepcie to limelitepcie
- All devices have now generic names
- Grouped device specific communication files into directories

Device Hierarchy after changes:
- Old
  /dev/limex30_control
  /dev/limex30_trx0
- New
  /dev/limelitepcie0/control0
  /dev/limelitepcie0/trx0
  /dev/limelitepcie0/trx1

2024-05-15 16:01 UTC, 9600 commented
Why "limelitepcie? Have we forked and modified LitePCIe? How do we benefit even from an SDR Linux device entry having "litepcie" in the naming? It feels needlessly long, but I'm probably missing something.

2024-05-15 19:05 UTC, rjonaitis commented
the name "limelitepcie" can be changed to anything, it just needs to be unique, suggestions are welcome. This choice was just a straigthforward "lime" prefix addition to the original "litepcie" name, as it is a modified version of it.
I'm not sure about the hardware side, but I think it is using the original litepcie as it is. On the software side, the driver code has been modified to our needs and forked from the original, to provide functionality specific to our devices that the original 'litepcie' does not have (like: device specific DMA channels count, and buffer sizes, other device VIDs/PIDs, specific device naming).

There are couple of reasons for the rename:
1. The kernel module name itself. The name has to be unique, to not clash with the original "litepcie" driver if it were already installed in the system, and both could be present at the same time.
2. The system device names in the `/dev` directory. Human readable and obvious names like "LimeSDR****" are convenient, but unwieldy. As that would require driver code update (just adding additional name string) for each new device released, even though the functionality of the driver remains the same. Also in case old drivers would detect newer devices by VID/PID but not have a human readable name assigned in that version, that would still require to have some kind of fallback name for such cases, or for the driver to ignore that device, and bring confusion why it is working.

The "/dev/limelitepcie*" nameing was chosen to be the same as the module name for consistency sake. It can also be changed to anything we want, it doesn't have to match the module name, suggestions are welcome. The requirement is that it needs to be unique from other system device names. As this generic device name is intended for any of our possible PCI devices, it wouldn't be technically correct to include SDR in the name, as it's functionality could be anything else. Just to clarify these names are for the system usage to allow it to work (like: sda, sdb, tty0, tty1, i2c-0, i2c-1.... they just indicate type of device and index ), human readable symlink names can be provided additionaly by using UDEV rules, or list the detailed info about devices using our CLI tools `limeDevice`

2024-05-16 10:08 UTC, rjonaitis requested changes

2024-05-16 10:08 UTC, rjonaitis commented on src/comms/PCIe/linux-kernel-module/limelitepcie.c
> +struct device *lime_device_create(const struct class *class, struct device *parent, dev_t devt, void *drvdata, const char *s)
unused function?

2024-05-16 10:08 UTC, rjonaitis commented on src/comms/PCIe/linux-kernel-module/limelitepcie.c
> +static void device_create_release(struct device *dev)
unused?

2024-05-16 10:08 UTC, rjonaitis commented on src/comms/PCIe/linux-kernel-module/boards.h
> +    "LimeSDR", // Unknown
Signify that it is recognized as LimeSDR, but unknown "LimeSDR-Unknown"

2024-05-16 10:08 UTC, rjonaitis commented on src/comms/PCIe/linux-kernel-module/limelitepcie.c
> +    if (0 < s->info.boardId && s->info.boardId < LMS_DEV_COUNT)
GetDeviceName already handles invalid values, returns unknown device name.

2024-05-16 10:08 UTC, rjonaitis commented on src/comms/PCIe/linux-kernel-module/limelitepcie.c
> +static void ParseIdentifier(char *identifier, char *destination)
identifier should be const.

2024-05-16 10:08 UTC, rjonaitis commented on src/comms/PCIe/linux-kernel-module/limelitepcie.c
> +    while (size < 256 && ValidChar(identifier[size]))
256 should be replaced with identifier length.

2024-05-16 10:08 UTC, rjonaitis commented on src/comms/PCIe/linux-kernel-module/limelitepcie.c
> +    strncpy(destination, identifier, size);
destination max length should be checked to not overflow the buffer.

2024-05-16 10:08 UTC, rjonaitis commented on src/comms/PCIe/linux-kernel-module/limelitepcie.c
> +    else if (ReadInfo(limelitepcie_dev) != 0)
log an error message if the ReadInfo fails.

2024-05-16 12:25 UTC, rjonaitis commented on src/comms/PCIe/LimeLitePCIe.cpp
> +    lsPipe = popen("ls -1 -- /sys/class/limelitepcie", "r");
if there is no pcie devices found by the driver, the /sys/class/limelitepcie directory will not exist and the "ls" command will print a error "ls: cannot access '/sys/class/limelitepcie': No such file or directory", the err stream should be discarded.

2024-05-16 14:00 UTC, rjonaitis approved these changes

2024-07-18 13:59 UTC, merged