Copy wxWidgets DLLs to the binary on build
myriadrf/LimeSuiteNG pull request #66
Opened 2024-07-02 12:55 UTC by DominykasPetke

# Added
- Automatically copy over wxWidgets DLLs on Windows to the binary directory to remove the need to manually copy them.

# Changed
- Updated wxWidgets used on Windows to 3.2.5

2024-07-02 13:54 UTC, rjonaitis requested changes
Doesn't work. Visual Studio 2022, dlls get copied into /bin directory. While the actual generated binaries are in /bin/Debug(or Release).

2024-07-02 13:54 UTC, rjonaitis commented on GUI/CMakeLists.txt
> +    # If 2017 or 2019
Comment why this is needed.

2024-07-03 06:48 UTC, DominykasPetke commented
I am unable to reproduce VS2022 creating the additional /Debug (or /Release) directory across two different VMs.

Yes, that directory gets created when using 2017 or 2019 build tools, but not with the 2022 ones.

Versions being used:
VS Build Tools 2017: 15.9.63
VS Build Tools 2019: 16.11.37
VS Community 2022: 17.10.3

2024-07-03 08:32 UTC, rjonaitis commented
with VS Community 2022: 17.10.3 I'm still getting Debug/Release directories.

By design MSVC is multi configuration, so it would always create Debug/Release subdirectories
[RUNTIME_OUTPUT_DIRECTORY_CONFIG](https://cmake.org/cmake/help/latest/prop_tgt/RUNTIME_OUTPUT_DIRECTORY_CONFIG.html#prop_tgt:RUNTIME_OUTPUT_DIRECTORY_%3CCONFIG%3E)
Multi-configuration generators ([Visual Studio](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators), [Xcode](https://cmake.org/cmake/help/latest/generator/Xcode.html#generator:Xcode), [Ninja Multi-Config](https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html#generator:Ninja%20Multi-Config)) append a per-configuration subdirectory to the specified directory unless a generator expression is used.

Also CMAKE_BUILD_TYPE_INIT is not really documented and is internal CMAKE variable, I think it could be replaced with using generator expressions.

2024-07-04 10:16 UTC, merged